spring:
  ai:
    model:
      embedding: ollama
    ollama:
      # 本地运行时使用（Testcontainers 会覆盖）
      base-url: http://localhost:11434
      embedding:
        options:
          model: all-minilm:l6-v2

logging:
  level:
    org.springframework.ai: DEBUG
